compatibility_date = "2024-11-06"
name = "short-url"
main = "src/index.ts"
minify = true

routes = [{ pattern = "x.jrg.tools", custom_domain = true }]

[vars]
NODE_ENV = "production"
DATABASE_URL_REPLICA = "file:local-replica.db"
DOMAIN = "x.jrg.tools"
